title: Oxford Star Trek Society
author: Kaashif Hymabaccus
email: kaashif dot hymabaccus at wadh dot ox dot ac dot uk
description:
  The Oxford Star Trek Society
baseurl: ""
url: "http://oxfordstartreksociety.co.uk"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
